### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by bf** [mckamey/countdown.js#11]
Sorry for spamming your inbox, but I wanted to say thanks for this great project. 

I have just found out that starting with 2.4 you display timespans between two UTC dates in the users' local time. As someone who is using 2.3.x in production this feature is godsent, and I am very happy to have the upgrades available. 

Thanks again for putting your effort into this project.

**Comment by mckamey** [comment]
Just to be clear, is this a 1) "thanks for displaying in local time" or a 2) "bug to revert to 2.3.x behavior"? I'm pretty sure it is 1), so I'm closing this as "You're welcome." :) Feel free to reopen if I misunderstood.
