### ISSUE TITLE
Upload countdown.js to a CDN

### ISSUE THREAD

**Issue by mckamey** [mckamey/countdown.js#2]
_Issue migrated from Bitbucket..._

Looks like [cdnjs](https://cdnjs.com/) have a pretty straightforward procedure for this:
https://github.com/cdnjs/cdnjs

**Comment by mckamey** [comment]
@ohadschn - looks like cdnjs is no longer a "straightforward" process!

https://github.com/cdnjs/cdnjs/issues/3638

The old way (manual pull request) is deprecated and the new way (npm / git auto-update) isn't actually working yet.

When it does work, I want to use `countdownjs` as the lib slug so that [it matches bower](bower.io/search/?q=countdownjs):

`ajax/libs/countdownjs/2.5.2/countdown.min.js`

**Comment by ohadschn** [comment]
Man, that sucks... 
Congrats on the move to GitHub though!

**Comment by mckamey** [comment]
This was satisfied almost a year ago: https://cdnjs.com/libraries/countdown
