### ISSUE TITLE
Feature: trigger function when end date reached

### ISSUE THREAD

**Issue by bkmorse** [mckamey/countdown.js#33]
I see the start and end params accept a callback function, but would it be possible to add another callback function for when the end date is reached.

So it can trigger some code when the end date is met. Maybe this already has that functionality? I just could not get it to do what I wanted.

**Comment by sehsarah** [comment]
I couldn't work this out either, i.e. when counting down to today, do something different at 0 (and past). Did you ever get this working with this lib? Thanks!

EDIT: Ended up doing this sort of logic within my requestAnimationFrame loop
```
 if ( start.isBefore(end) ) {
   // countdown reveal
 }
```

Would be cool to add some docs or methods for use with this use case though - 👍

**Comment by mckamey** [comment]
The [readme](http://countdownjs.org/readme.html) specifically calls out how to tell if the event was in the past:

> ### Timespan result
> The return value is a Timespan object which always contains the following fields:
>
> `Number value`: total milliseconds difference (i.e., `end - start`). If `end < start` then `value` will be negative.
>
> Typically the `end` occurs after `start`, but if the arguments were reversed, the only difference is `Timespan.value` will be negative. The sign of `value` can be used to determine if the event occurs in the future or in the past.

If `value` is zero then the time event is "now". That is demonstrated in the demo.
