### ISSUE TITLE
is:issue is:open How to use the end date/time callback

### ISSUE THREAD

**Issue by codyng** [mckamey/countdown.js#34]
The api spec from the doc is: var timespan = countdown(start|callback, end|callback, units, max, digits);

If I specify the end callback function, there is javascript error or can't be compiled. How to use the "end event callback" indeed??

I would like to stop the countdown once it reaches the date or time.
Many thanks,

**Comment by mckamey** [comment]
Please show some example code. If there is a compilation error that is likely because of a syntax error in your code. You can reopen if this is still an issue.
