### ISSUE TITLE
Use no labels

### ISSUE THREAD

**Issue by dialogik** [mckamey/countdown.js#4]
I want to use a time format like this

```
12:34:56 /* hours:minutes:seconds */
```

So I can only do this by overriding it by blank spaces like this

```
countdown.setLabels(
    ' | | | | | | | | | | ',
    ' | | | | | | | | | | ',
    ':',
    ':',
    null);
```

Because if I would use `'||||||||||'` (without blank spaces) the script would think I don't want to override. But now I have an output with blank spaces like this

```
12 :34 :56
```

How can I remove the blank spaces (without a JavaScript string replace workaround)?

**Comment by mckamey** [comment]
Sorry I thought I'd already replied to this. Your use case is significantly different than the expected, so I think it would complicate it too much to try to generalize it for this situation. However, it is trivial to implement with a custom callback method. Something like this would close #4 and #5:

``` javascript
// Formats integers to have at least two digits.
function f(n) { return n<10 ? '0'+n : n; }

countdown(new Date(Date.now() + (12*60*60*1000)), function(ts) {
  console.log((ts.hours||'0')+':'+f(ts.minutes)+':'+f(ts.seconds));
}, countdown.HOURS|countdown.MINUTES|countdown.SECONDS);
```

**Comment by dialogik** [comment]
That looks doable, thanks for the update!
