### ISSUE TITLE
Unnecessary comma in generated text

### ISSUE THREAD

**Issue by th0r** [mckamey/countdown.js#6]
Thanks for package!

Found one tiny but annoying bug:
code `countdown(null, Date.now() + 135 * 1000)` returns `2 minutes, and 15 seconds`.

Comma here is unnecessary.

**Comment by mckamey** [comment]
It is possible to configure it that way but it isn't the default. Are you sure are using the latest version?

**Comment by th0r** [comment]
`$ node`:

``` js
> var countdown = require('countdown');
undefined
> require('countdown/package.json').version
'2.3.0'
> countdown(null, Date.now() + 135 * 1000).toString()
'2 minutes, and 15 seconds'
```

**Comment by th0r** [comment]
Ah, I see! The latest version in npm is `2.3.0`. @mckamey do you mind publishing `2.5.2`?

**Comment by th0r** [comment]
@mckamey ping!

**Comment by mckamey** [comment]
pong.
